export const personnelData = [
  { name: "Bayy A Bimantara", rank: "JENDERAL", position: "KEPALA KEPOLISIAN", division: "SABHARA" },
  { name: "Mangkuluhur Bimantara", rank: "KOMJEN", position: "WAKIL KEPALA KEPOLISIAN", division: "SABHARA" },
  { name: "Shenna L Bimantara", rank: "BRIGJEN", position: "SEKJEN", division: "SABHARA" },
  { name: "Kuro Schmith", rank: "IRJEN", position: "KADIV", division: "PROPAM" },
  { name: "Oliver Bimantara Jayaprawira Kalimoesodo", rank: "BRIGJEN", position: "WAKADIV", division: "PROPAM" },
  { name: "Ucup Lioon", rank: "IRJEN", position: "KADIV", division: "BRIMOB" },
  { name: "Marco Higgins", rank: "BRIGJEN", position: "WAKADIV", division: "BRIMOB" },
  { name: "Alexander Joshua Morty", rank: "IRJEN", position: "KADIV", division: "SABHARA" },
  { name: "Natan Higgins", rank: "IPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Serlut Hanagami", rank: "BRIPTU", position: "ANGGOTA", division: "SABHARA" },
  { name: "Apta Redfield", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Theo Bimantara", rank: "BRIPTU", position: "ANGGOTA", division: "SABHARA" },
  { name: "Batlas Keriput", rank: "BRIPTU", position: "ANGGOTA", division: "SABHARA" },
  { name: "Wayne B.", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Yera Jeveya Kalimoesodo", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Pico Cobra", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Tedrick Maxwell Deluca", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "LAIZER S", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Derry Gillbert", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "John With", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Malik Elliot", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Calleb", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Garry Valerian", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Prabowo Fahhot", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Perdi Sambog", rank: "TAMTAMA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Alex Sandra", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Mateo Kingsly", rank: "BRIPDA", position: "ANGGOTA", division: "SABHARA" },
  { name: "Hazama Xavi", rank: "IRJEN", position: "KADIV", division: "KORLANTAS" },
  { name: "Rico Johanson", rank: "BRIGJEN", position: "WAKADIV", division: "KORLANTAS" },
  { name: "Alip Beceng", rank: "IPDA", position: "ANGGOTA", division: "KORLANTAS" },
  { name: "John Bul Bul", rank: "BRIPDA", position: "ANGGOTA", division: "KORLANTAS" },
  { name: "Kai Orsix", rank: "IRJEN", position: "KADIV", division: "RESKRIM" },
  { name: "Xentino Kimochi", rank: "IPDA", position: "ANGGOTA", division: "RESKRIM" },
];
